before_script:
  - docker info
  - whoami
stages:
  - build_image
  - deploy_liantiao

build_job:
  stage: build_image
  script:
    - echo $CI_COMMIT_SHORT_SHA $CI_PROJECT_PATH $CI_PROJECT_NAME
    - docker build --no-cache -f Dockerfile -t harbor.ymt.io/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA .
    - sudo docker push harbor.ymt.io/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA
  only:
    - liantiao
  tags:
    - dev-host-k8s-master

deploy_job:
  stage: deploy_liantiao
  script:
    - cd /home/gitlab-runner
    - bash liantiao_deployment.sh $CI_PROJECT_NAME
  only:
    - liantiao
  tags:
    - dev-host-k8s-master