ServiceName = "test_mysql"

[master]
Host = "127.0.0.1"
Port = "3306"
User = "root"
Password = "123456"
DB = "test"
Charset = "utf8mb4"
MaxOpen = 8
MaxIdle = 4

[slave]
Host = "127.0.0.1"
Port = "3306"
User = "root"
Password = "123456"
DB = "test"
Charset = "utf8mb4"
MaxOpen = 8
MaxIdle = 4